site_name: "ggtree"
site_url: http://guangchuangyu.github.io/ChIPseeker
site_author: Guangchuang Yu
repo_url: https://github.com/GuangchuangYu/ChIPseeker
pages:
- Home: index.md
- Featured Articles: featuredArticles.md

copyright: Copyright &copy; 2016 <a href="http://guangchuangyu.github.io">Guangchuang Yu</a>.
